# Generated by Django 4.2.13 on 2026-05-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalrequest',
            name='customer',
        ),
    ]
