# Generated by Django 4.2.13 on 2026-05-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0015_ring_tracking'),
        ('approvals', '0002_remove_approvalrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='call',
            field=models.ForeignKey(blank=True, help_text='Auto-linked when the approval is requested during a live call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='calls.call'),
        ),
    ]
