# Generated by Django 4.2.13 on 2026-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_add_approval_call_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='creation_reason',
            field=models.TextField(blank=True, help_text='Why this approval was requested (auto-filled from call note if linked)'),
        ),
    ]
