# Generated by Django 4.2.13 on 2026-05-12 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0015_ring_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0004_add_approval_creation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalCallLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('originating', 'Originating Call'), ('auto_during_call', 'Auto-linked During Call'), ('manual', 'Manually Linked')], default='auto_during_call', max_length=20)),
                ('action_summary', models.TextField(blank=True, default='')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_links', to='approvals.approvalrequest')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_links', to='calls.call')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_call_links_created', to=settings.AUTH_USER_MODEL)),
                ('unlinked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_call_links_unlinked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approvals_call_link',
                'ordering': ['-linked_at'],
                'indexes': [models.Index(fields=['approval', 'unlinked_at'], name='approvals_c_approva_f2f6eb_idx'), models.Index(fields=['call'], name='approvals_c_call_id_45fbbe_idx')],
                'unique_together': {('approval', 'call')},
            },
        ),
    ]
