# Generated by Django 4.2.13 on 2026-03-22 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_rename_customers_name_idx_customers_first_n_93c9ec_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0007_fix_callee_caller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, max_length=10, unique=True)),
                ('first_response_hrs', models.PositiveIntegerField(default=4)),
                ('resolution_hrs', models.PositiveIntegerField(default=24)),
                ('business_hours_only', models.BooleanField(default=False, help_text='Calculate SLA only during business hours')),
                ('work_start_hour', models.PositiveSmallIntegerField(default=9)),
                ('work_end_hour', models.PositiveSmallIntegerField(default=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SLA Policy',
                'verbose_name_plural': 'SLA Policies',
                'db_table': 'tickets_sla_policy',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tickets_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ticket_type', models.CharField(choices=[('complaint', 'Complaint'), ('request', 'Request'), ('inquiry', 'Inquiry')], db_index=True, default='inquiry', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('source', models.CharField(choices=[('call', 'Phone Call'), ('manual', 'Manual (Agent)'), ('email', 'Email'), ('portal', 'Customer Portal'), ('system', 'System (Auto)')], db_index=True, default='manual', max_length=20)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=30)),
                ('phone_number_normalized', models.CharField(blank=True, db_index=True, max_length=20)),
                ('asterisk_call_id', models.CharField(blank=True, db_index=True, help_text='Raw Asterisk UniqueID string', max_length=100)),
                ('queue', models.CharField(blank=True, db_index=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.CharField(blank=True, max_length=255)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolution_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sla_breached', models.BooleanField(db_index=True, default=False)),
                ('sla_response_breached', models.BooleanField(default=False)),
                ('is_escalated', models.BooleanField(db_index=True, default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_note', models.TextField(blank=True)),
                ('note_count', models.PositiveIntegerField(default=0)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Flexible key-value store for custom fields')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='calls.call')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='customers.customer')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_tickets', to=settings.AUTH_USER_MODEL)),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.slapolicy')),
                ('tags', models.ManyToManyField(blank=True, related_name='tickets', to='tickets.tag')),
            ],
            options={
                'db_table': 'tickets_ticket',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('public', 'Public')], db_index=True, default='internal', max_length=10)),
                ('is_first_response', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_notes', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets_note',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_history_actions', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket')),
            ],
            options={
                'db_table': 'tickets_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('attachment_type', models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('call_recording', 'Call Recording')], db_index=True, default='file', max_length=20)),
                ('asterisk_call_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to='calls.call')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='tickets.ticketnote')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets_attachment',
            },
        ),
        migrations.AddIndex(
            model_name='ticketnote',
            index=models.Index(fields=['ticket', 'visibility'], name='idx_note_ticket_visibility'),
        ),
        migrations.AddIndex(
            model_name='ticketnote',
            index=models.Index(fields=['ticket', '-created_at'], name='idx_note_ticket_created'),
        ),
        migrations.AddIndex(
            model_name='tickethistory',
            index=models.Index(fields=['ticket', '-created_at'], name='idx_history_ticket_created'),
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket', 'attachment_type'], name='idx_attach_ticket_type'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'priority'], name='idx_ticket_status_priority'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['agent', 'status', '-updated_at'], name='idx_ticket_agent_status_upd'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer', 'status'], name='idx_ticket_customer_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='idx_ticket_status_created'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['resolution_deadline'], name='idx_ticket_resolution_dl'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sla_breached', 'status'], name='idx_ticket_sla_breached'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['source', 'status'], name='idx_ticket_source_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_escalated', 'status'], name='idx_ticket_escalated'),
        ),
    ]
