# Generated by Django 4.2.13 on 2026-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='direction',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], db_index=True, max_length=10, null=True),
        ),
    ]
