# Generated by Django 4.2.13 on 2026-05-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_merge_customer_fields'),
        ('tickets', '0002_add_direction_to_ticket'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='idx_ticket_customer_status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.AddField(
            model_name='ticket',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['lead', 'status'], name='idx_ticket_lead_status'),
        ),
    ]
