# Generated by Django 4.2.13 on 2026-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_idx_ticket_customer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creation_reason',
            field=models.TextField(blank=True, help_text='Why this ticket was opened (auto-filled from call note if linked)'),
        ),
    ]
