# Generated by Django 4.2.13 on 2026-05-12 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0015_ring_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_add_ticket_creation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='history_call',
            field=models.ForeignKey(blank=True, help_text='The call active when this change occurred (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_history_entries', to='calls.call'),
        ),
        migrations.CreateModel(
            name='TicketCallLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('originating', 'Originating Call'), ('auto_during_call', 'Auto-linked During Call'), ('manual', 'Manually Linked')], default='auto_during_call', max_length=20)),
                ('action_summary', models.TextField(blank=True, default='', help_text="Short summary of what happened (e.g. 'Status: open → in_progress')")),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='calls.call')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_call_links_created', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_links', to='tickets.ticket')),
                ('unlinked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_call_links_unlinked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets_ticket_call_link',
                'ordering': ['-linked_at'],
                'indexes': [models.Index(fields=['ticket', 'unlinked_at'], name='tickets_tic_ticket__98248d_idx'), models.Index(fields=['call'], name='tickets_tic_call_id_71e4a7_idx')],
                'unique_together': {('ticket', 'call')},
            },
        ),
    ]
