# Generated by Django 4.2.13 on 2026-03-27 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0001_initial'),
        ('customers', '0002_rename_customers_name_idx_customers_first_n_93c9ec_idx_and_more'),
        ('leads', '0009_add_lead_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('per_unit', 'Per Unit (m², ml, kg, hr …)'), ('variants', 'Has Variants')], default='fixed', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('m2', 'm²'), ('ml', 'ml'), ('kg', 'kg'), ('hour', 'Hour'), ('other', 'Other')], default='piece', max_length=10)),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_type', models.CharField(choices=[('price_quote', 'Price Quotation'), ('contract', 'Contract / Agreement')], db_index=True, default='price_quote', max_length=15)),
                ('ref_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revision', 'Revision Requested')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=14.0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('terms_body', models.TextField(blank=True, help_text='Rendered terms after placeholder substitution')),
                ('internal_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='approvals.approvalrequest')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='customers.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='leads.lead')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='sales.quotation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_price_quotation', models.BooleanField(default=True)),
                ('enable_contract', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='sales/logos/')),
                ('company_address', models.TextField(blank=True)),
                ('default_currency', models.CharField(default='EGP', max_length=10)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=14.0, max_digits=5)),
                ('quotation_prefix', models.CharField(default='QUO', max_length=10)),
                ('next_quotation_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'sales_settings',
            },
        ),
        migrations.CreateModel(
            name='TermsTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('real_estate', 'Real Estate'), ('legal', 'Legal'), ('other', 'Other')], default='standard', max_length=20)),
                ('body', models.TextField(help_text='Use {{placeholder}} for dynamic values')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_terms_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sales.quotation')),
            ],
            options={
                'db_table': 'sales_quotation_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation')),
            ],
            options={
                'db_table': 'sales_quotation_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuotationField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sales.quotation')),
            ],
            options={
                'db_table': 'sales_quotation_fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sales.product')),
            ],
            options={
                'db_table': 'sales_product_variants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDimensionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_fields', to='sales.product')),
            ],
            options={
                'db_table': 'sales_product_dimension_fields',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status', '-created_at'], name='idx_quot_status_created'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['agent', 'status'], name='idx_quot_agent_status'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer'], name='idx_quot_customer'),
        ),
    ]
