# Generated by Django 4.2.13 on 2026-05-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quotation',
            name='idx_quot_customer',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['lead'], name='idx_quot_lead'),
        ),
    ]
