# Generated by Django 4.2.13 on 2026-05-12 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0015_ring_tracking'),
        ('sales', '0002_remove_quotation_idx_quot_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='call',
            field=models.ForeignKey(blank=True, help_text='Call this quotation was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='calls.call'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='creation_reason',
            field=models.TextField(blank=True, help_text='Why this quotation was created (e.g. customer request during call)'),
        ),
    ]
