# Generated by Django 4.2.13 on 2026-05-12 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0015_ring_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_add_quotation_call_and_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlog',
            name='log_call',
            field=models.ForeignKey(blank=True, help_text='The call active when this log entry was created (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_log_entries', to='calls.call'),
        ),
        migrations.CreateModel(
            name='QuotationCallLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('originating', 'Originating Call'), ('auto_during_call', 'Auto-linked During Call'), ('manual', 'Manually Linked')], default='auto_during_call', max_length=20)),
                ('action_summary', models.TextField(blank=True, default='')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_links', to='calls.call')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_call_links_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_links', to='sales.quotation')),
                ('unlinked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_call_links_unlinked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_quotation_call_link',
                'ordering': ['-linked_at'],
                'indexes': [models.Index(fields=['quotation', 'unlinked_at'], name='sales_quota_quotati_6bb081_idx'), models.Index(fields=['call'], name='sales_quota_call_id_7a6d24_idx')],
                'unique_together': {('quotation', 'call')},
            },
        ),
    ]
