# Generated by Django 4.2.13 on 2026-03-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_call_campaign'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_status_0ea02e_idx',
            old_name='calls_status_agent_idx',
        ),
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_started_783431_idx',
            old_name='calls_started_at_idx',
        ),
        migrations.RenameIndex(
            model_name='call',
            new_name='calls_caller__609c68_idx',
            old_name='calls_caller_idx',
        ),
        migrations.RemoveField(
            model_name='call',
            name='campaign',
        ),
    ]
