# Generated by Django 4.2.13 on 2026-03-16 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_fix_call_models'),
        ('followups', '0002_rename_followups_status_idx_followups_status_bbf28b_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0004_call_completion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='callcompletion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='callevent',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='disposition',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='call',
            name='calls_caller__609c68_idx',
        ),
        migrations.RenameField(
            model_name='callcompletion',
            old_name='followup_assigned_to',
            new_name='followup_assigned',
        ),
        migrations.RenameField(
            model_name='callcompletion',
            old_name='update_lead_stage',
            new_name='lead_stage_updated',
        ),
        migrations.RenameField(
            model_name='calldisposition',
            old_name='notes',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='call',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='call',
            name='callee_number',
        ),
        migrations.RemoveField(
            model_name='call',
            name='caller_number',
        ),
        migrations.RemoveField(
            model_name='call',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='call',
            name='linkedid',
        ),
        migrations.RemoveField(
            model_name='call',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='call',
            name='recording_file',
        ),
        migrations.RemoveField(
            model_name='call',
            name='recording_url',
        ),
        migrations.RemoveField(
            model_name='call',
            name='wait_time',
        ),
        migrations.RemoveField(
            model_name='callcompletion',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='callcompletion',
            name='new_stage',
        ),
        migrations.RemoveField(
            model_name='calldisposition',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='disposition',
            name='description',
        ),
        migrations.AddField(
            model_name='call',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='callcompletion',
            name='followup_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_completion', to='followups.followup'),
        ),
        migrations.AddField(
            model_name='callcompletion',
            name='new_lead_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_completions', to='leads.leadstage'),
        ),
        migrations.AddField(
            model_name='callcompletion',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callcompletion',
            name='submitted_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='call',
            name='callee',
            field=models.CharField(max_length=50, blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='call',
            name='caller',
            field=models.CharField(max_length=50, blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='call',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], default='outbound', max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='queue',
            field=models.CharField(blank=True, default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('completed', 'Completed')], default='ringing', max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='callcompletion',
            name='followup_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='callcompletion',
            name='next_action',
            field=models.CharField(choices=[('callback', 'Schedule Callback'), ('send_quotation', 'Send Quotation'), ('followup_later', 'Follow-up Later'), ('close_lead', 'Close Lead'), ('no_action', 'No Action Required')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calldisposition',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='calls.call'),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='callevent',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='calls.call'),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='color',
            field=models.CharField(default='#6b7280', max_length=20),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='default_next_action',
            field=models.CharField(choices=[('callback', 'Schedule Callback'), ('send_quotation', 'Send Quotation'), ('followup_later', 'Follow-up Later'), ('close_lead', 'Close Lead'), ('no_action', 'No Action Required')], default='no_action', max_length=50),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
