# Generated by Django 4.2.13 on 2026-03-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0005_fix_call_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='callee',
            field=models.CharField(max_length=50, blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='call',
            name='caller',
            field=models.CharField(max_length=50, blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='callcompletion',
            name='submitted_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='call',
                    index=models.Index(fields=['caller'], name='calls_caller__609c68_idx'),
                ),
            ],
        ),
    ]
