# Generated by Django 4.2.13 on 2026-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_fix_caller_fields_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='callee',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='call',
            name='caller',
            field=models.CharField(max_length=50),
        ),
    ]
