# Generated by Django 4.2.13 on 2026-03-25 04:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_fix_callee_caller'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposition',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='disposition',
            name='requires_note',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='default_next_action',
            field=models.CharField(default='no_action', max_length=50),
        ),
        migrations.CreateModel(
            name='DispositionAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('no_action', 'No Action'), ('create_followup', 'Create Follow-up'), ('create_lead', 'Create Lead'), ('create_ticket', 'Create Ticket'), ('change_lead_stage', 'Change Lead Stage'), ('mark_won', 'Mark Lead as Won'), ('escalate', 'Escalate to Supervisor')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='calls.disposition')),
            ],
            options={
                'db_table': 'disposition_actions',
                'ordering': ['order'],
            },
        ),
    ]
