# Generated by Django 4.2.13 on 2026-05-03 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0004_remove_customer_from_followup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0009_add_lead_events'),
        ('calls', '0008_add_disposition_direction_and_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('trigger', models.CharField(choices=[('missed_call', 'Missed Call'), ('no_answer', 'No Answer'), ('vip_call', 'VIP Incoming Call'), ('long_call', 'Call Exceeds Duration')], max_length=30)),
                ('action', models.CharField(choices=[('create_callback', 'Create Callback Task'), ('notify_manager', 'Notify Manager/Supervisor'), ('send_sms', 'Send SMS'), ('assign_priority', 'Assign Priority')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Rule-specific config (e.g. delay_hours, vip_tags)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'automation_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uniqueid', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('incoming', 'Incoming Call'), ('answered', 'Call Answered'), ('ended', 'Call Ended'), ('recording', 'Recording Ready')], max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'webhook_events',
                'unique_together': {('uniqueid', 'event_type')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('followup', 'Follow-up'), ('note', 'Note'), ('email', 'Email'), ('sms', 'SMS')], max_length=15)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=15)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='calls.call')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='followups.followup')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['lead', 'activity_type'], name='activities_lead_id_bb74b7_idx'), models.Index(fields=['lead', 'status'], name='activities_lead_id_d3c9a1_idx'), models.Index(fields=['lead', 'started_at'], name='activities_lead_id_2a768c_idx')],
            },
        ),
    ]
