# Generated by Django 4.2.13 on 2026-05-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0009_automationrule_webhookevent_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='customer',
        ),
    ]
