# Generated by Django 4.2.13 on 2026-05-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0010_remove_call_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='caller_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
