# Generated by Django 4.2.13 on 2026-05-05 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0011_add_caller_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAgentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('offered', 'Call Offered'), ('answered', 'Call Answered'), ('rejected', 'Call Rejected'), ('timeout', 'Ring Timeout'), ('ringhangup', 'Agent Hung Up While Ringing')], db_index=True, max_length=20)),
                ('ring_duration', models.PositiveIntegerField(default=0, help_text="Seconds the agent's phone rang before this event")),
                ('note', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_agent_events', to=settings.AUTH_USER_MODEL)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_events', to='calls.call')),
            ],
            options={
                'db_table': 'call_agent_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['call', 'event_type'], name='call_agent__call_id_4aeeef_idx'), models.Index(fields=['agent', 'event_type'], name='call_agent__agent_i_8784c6_idx'), models.Index(fields=['created_at'], name='call_agent__created_0936db_idx')],
            },
        ),
    ]
