# Generated by Django 4.2.13 on 2026-05-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_add_call_agent_events_and_lead_call_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callagentevent',
            name='event_type',
            field=models.CharField(choices=[('offered', 'Call Offered'), ('popup_shown', 'Popup Shown to Agent'), ('answered', 'Call Answered'), ('rejected', 'Call Rejected'), ('dismissed', 'Popup Dismissed (X button)'), ('timeout', 'Ring Timeout'), ('ringhangup', 'Agent Hung Up While Ringing'), ('transfer_init', 'Transfer Initiated'), ('hold_started', 'Call Put On Hold'), ('hold_ended', 'Call Resumed from Hold'), ('mute_toggled', 'Mute Toggled')], db_index=True, max_length=20),
        ),
    ]
