# Generated by Django 4.2.13 on 2026-05-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0014_alter_callagentevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='answered_at',
            field=models.DateTimeField(blank=True, help_text='When call was answered (Bridge/AgentConnect)', null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='no_answer_reason',
            field=models.CharField(blank=True, default='', help_text='agent_timeout | caller_abandoned | empty for answered calls', max_length=24),
        ),
        migrations.AddField(
            model_name='call',
            name='ring_duration',
            field=models.IntegerField(default=0, help_text='Seconds spent ringing before answer or hangup'),
        ),
        migrations.AddField(
            model_name='call',
            name='ringing_started_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When channel started ringing (Newchannel/QueueCallerJoin)', null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='talk_duration',
            field=models.IntegerField(default=0, help_text='Seconds of actual conversation (answered → ended)'),
        ),
    ]
