# Generated by Django 4.2.13 on 2026-03-16 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationsetting',
            options={'ordering': ['key']},
        ),
        migrations.RemoveField(
            model_name='integrationsetting',
            name='description',
        ),
        migrations.AddField(
            model_name='integrationsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integrationsetting',
            name='key',
            field=models.CharField(choices=[('ami_host', 'AMI Host'), ('ami_port', 'AMI Port'), ('ami_username', 'AMI Username'), ('ami_secret', 'AMI Secret (encrypted)'), ('recording_url', 'Recording Base URL'), ('cdr_sync', 'CDR Sync Enabled'), ('cdr_db_host', 'CDR DB Host'), ('cdr_db_name', 'CDR DB Name')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='integrationsetting',
            name='value',
            field=models.TextField(),
        ),
    ]
