# Generated by Django 4.2.13 on 2026-03-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['category', 'key']},
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='group',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('telephony', 'Telephony'), ('security', 'Security'), ('notifications', 'Notifications')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Expose to non-admin API consumers'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=models.TextField(),
        ),
    ]
