# Generated by Django 4.2.13 on 2026-03-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_core', '0002_alter_systemsetting_options_and_more'),
        ('settings_core', '0003_seed_default_settings'),
    ]

    operations = [
    ]
