# Generated by Django 4.2.13 on 2026-05-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='customer',
        ),
    ]
