# Generated by Django 4.2.13 on 2026-03-16 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='savedreport',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='report_type',
            field=models.CharField(choices=[('agent_performance', 'Agent Performance'), ('call_summary', 'Call Summary'), ('lead_pipeline', 'Lead Pipeline'), ('followup_rate', 'Follow-up Rate'), ('campaign_stats', 'Campaign Stats')], max_length=30),
        ),
    ]
