# Generated by Django 4.2.13 on 2026-03-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='followup',
            new_name='followups_status_bbf28b_idx',
            old_name='followups_status_idx',
        ),
    ]
