# Generated by Django 4.2.13 on 2026-03-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_name_idx_customers_first_n_93c9ec_idx_and_more'),
        ('followups', '0002_rename_followups_status_idx_followups_status_bbf28b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='customers.customer'),
        ),
    ]
