# Generated by Django 4.2.13 on 2026-03-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_make_customer_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='customer',
        ),
    ]
