# Generated by Django 4.2.13 on 2026-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0004_remove_customer_from_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='creation_reason',
            field=models.TextField(blank=True, help_text='Why this followup was scheduled (auto-filled from call note if linked)'),
        ),
    ]
