# Generated by Django 4.2.13 on 2026-03-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_extension_peer_name_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='vicidial_campaign',
            field=models.CharField(blank=True, help_text='VICIdial campaign ID (e.g. 2000)', max_length=50),
        ),
        migrations.AddField(
            model_name='extension',
            name='vicidial_ingroup',
            field=models.CharField(blank=True, help_text='VICIdial ingroup ID (e.g. 901)', max_length=50),
        ),
        migrations.AddField(
            model_name='extension',
            name='vicidial_pass',
            field=models.CharField(blank=True, help_text='VICIdial user password', max_length=100),
        ),
        migrations.AddField(
            model_name='extension',
            name='vicidial_user',
            field=models.CharField(blank=True, help_text='VICIdial username (usually same as extension number)', max_length=50),
        ),
    ]
