# Generated by Django 4.2.13 on 2026-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_vicidial_fields_to_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='queues',
            field=models.ManyToManyField(blank=True, help_text='Asterisk queues this agent belongs to', related_name='members', to='users.queue'),
        ),
    ]
