# Generated by Django 4.2.13 on 2026-03-23 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_queues_m2m_to_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_sessions',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_start', models.DateTimeField(auto_now_add=True)),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(default='Break', max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='users.agentsession')),
            ],
            options={
                'db_table': 'agent_breaks',
                'ordering': ['-break_start'],
            },
        ),
    ]
