# Generated by Django 4.2.13 on 2026-03-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_agent_session_break_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_since',
            field=models.DateTimeField(blank=True, help_text='When the current status started', null=True),
        ),
    ]
