# Generated by Django 4.2.13 on 2026-03-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_campaign'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_status__64a296_idx',
            old_name='leads_status_agent_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_followu_b0a7a5_idx',
            old_name='leads_followup_idx',
        ),
    ]
