# Generated by Django 4.2.13 on 2026-03-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leadstage_add_missing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadpriority',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_status__64a296_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='leadpriority',
            name='color',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='is_won',
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lost_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadpriority'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('call', 'Inbound Call'), ('campaign', 'Campaign'), ('referral', 'Referral'), ('web', 'Website'), ('other', 'Other')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadstatus'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leadpriority',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leadstage',
            name='color',
            field=models.CharField(default='#6b7280', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadstage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='color',
            field=models.CharField(default='#6b7280', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
