# Generated by Django 4.2.13 on 2026-03-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_fix_lead_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage', 'assigned_to'], name='leads_status__64a296_idx'),
        ),
    ]
