# Generated by Django 4.2.13 on 2026-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_fix_call_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstage',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
