# Generated by Django 4.2.13 on 2026-03-25 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0008_slug_free_text_auto_generate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('stage_changed', 'Stage Changed'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('followup_set', 'Follow-up Scheduled'), ('won', 'Won'), ('lost', 'Lost'), ('note', 'Note Added')], max_length=30)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
