# Generated by Django 4.2.13 on 2026-03-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_add_lead_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='classification',
            field=models.CharField(choices=[('none', 'None'), ('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('very_hot', 'Very Hot')], db_index=True, default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, default='Egypt', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='lifecycle_stage',
            field=models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('opportunity', 'Opportunity'), ('customer', 'Customer'), ('churned', 'Churned')], db_index=True, default='lead', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
