# Generated by Django 4.2.13 on 2026-03-29 01:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_add_contact_lifecycle_score_to_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('call_long', 'Call > 3 min'), ('call_short', 'Call < 3 min'), ('call_no_answer', 'Call No Answer'), ('followup_responded', 'Followup Responded'), ('followup_missed', 'Followup Missed'), ('quotation_sent', 'Quotation Sent'), ('quotation_accepted', 'Quotation Accepted'), ('quotation_rejected', 'Quotation Rejected'), ('profile_complete', 'Profile Completed'), ('time_decay', 'Time Decay'), ('manual', 'Manual Adjustment')], max_length=30)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_score_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
