# Generated by Django 4.2.13 on 2026-04-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_add_score_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ التحويل لكاستمر', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_to_customer',
            field=models.BooleanField(db_index=True, default=False, help_text='تم تحويله لكاستمر بعد WON'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['converted_to_customer', 'lifecycle_stage'], name='leads_converted_lifecycle_idx'),
        ),
    ]
