# Generated by Django 4.2.13 on 2026-05-03 05:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_merge_customer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
            ],
            options={
                'db_table': 'lead_tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Primary phone — used for incoming call lookup', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.leadtag'),
        ),
    ]
