# Generated by Django 4.2.13 on 2026-05-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_classification_lead_converted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('stage_changed', 'Stage Changed'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('followup_set', 'Follow-up Scheduled'), ('won', 'Won'), ('lost', 'Lost'), ('note', 'Note Added'), ('call_offered', 'Call Offered'), ('call_answered', 'Call Answered'), ('call_rejected', 'Call Rejected'), ('call_no_answer', 'Call No Answer')], max_length=30),
        ),
    ]
