# Generated by Django 4.2.13 on 2026-05-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_add_call_agent_events_and_lead_call_events'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_name_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='title',
        ),
        migrations.AddField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, help_text='Lead display name', max_length=255),
        ),
    ]
