# Generated by Django 4.2.13 on 2026-05-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_reconcile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('stage_changed', 'Stage Changed'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('followup_set', 'Follow-up Scheduled'), ('won', 'Won'), ('lost', 'Lost'), ('note', 'Note Added'), ('note_added', 'Note Added'), ('call_offered', 'Call Offered'), ('call_answered', 'Call Answered'), ('call_rejected', 'Call Rejected'), ('call_no_answer', 'Call No Answer'), ('quotation_created', 'Quotation Created'), ('quotation_sent', 'Quotation Sent'), ('quotation_approved', 'Quotation Approved'), ('quotation_rejected', 'Quotation Rejected'), ('quotation_accepted', 'Quotation Accepted'), ('approval_requested', 'Approval Requested'), ('approval_approved', 'Approval Approved'), ('approval_rejected', 'Approval Rejected'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed')], max_length=30),
        ),
    ]
