# Generated by Django 4.2.13 on 2026-03-26 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0004_remove_customer_from_followup'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='action_type',
            field=models.CharField(choices=[('call_lead', 'Call Lead'), ('send_email', 'Send Email'), ('follow_up', 'Follow Up'), ('send_offer', 'Send Offer'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='followups.followup'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_at',
            field=models.DateTimeField(blank=True, help_text='When to remind the agent about this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
