# Generated by Django 4.2.13 on 2026-05-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_action_type_task_followup_task_reminder_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='customer',
        ),
    ]
