# Generated by Django 4.2.13 on 2026-03-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignmember_last_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignmember',
            name='last_call',
        ),
    ]
