# Generated by Django 4.2.13 on 2026-05-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_phone_nullable'),
        ('campaigns', '0003_remove_campaignmember_last_call'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignmember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campaignmember',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmember',
            unique_together={('campaign', 'lead')},
        ),
        migrations.RemoveField(
            model_name='campaignmember',
            name='customer',
        ),
    ]
