# Generated by Django 4.2.13 on 2026-03-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_first_n_93c9ec_idx',
            old_name='customers_name_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, help_text='Where this customer came from', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerphone',
            name='normalized',
            field=models.CharField(blank=True, db_index=True, help_text='E.164 normalized number', max_length=30),
        ),
    ]
